project_id = "uzxwawsybsnnyuoohkxo"

[functions.auto-renew-subscriptions]
verify_jwt = false

[functions.paypal-checkout]
verify_jwt = false

[functions.create-google-meet]
verify_jwt = false

[functions.send-consultation-reminders]
verify_jwt = false
